### ISSUE TITLE
Error on loading library list

### ISSUE THREAD

**Issue by rabelux** [ukdtom/ExportTools.bundle#103]
ExportTools: V 2.0.0.5
PMS: V 1.16.5.1488 (latest)
Plex Web: 3.108.2
System: ASUSTOR NAS

Hi Tommy,
every few years i maintain my library and that's when plex2csv/exporttools come into play.

So I installed it as mentioned in the wiki but when loading the libraries nothing happens.
Log shows following error:
```
CRITICAL (sandbox:303) - Exception when calling function 'ValidatePrefs' (most recent call last):
  File "/volume1/.@plugins/AppCentral/plexmediaserver/Resources/Plug-ins-deeb86e7f/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/volume1/Plex/Library/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 408, in ValidatePrefs
    Thread.Create(sectionList(), globalize=True)
  File "/volume1/.@plugins/AppCentral/plexmediaserver/Resources/Plug-ins-deeb86e7f/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/threadkit.py", line 54, in Create
    return self._core.runtime.create_thread(f, True, self._sandbox, globalize, *args, **kwargs)
  File "/volume1/.@plugins/AppCentral/plexmediaserver/Resources/Plug-ins-deeb86e7f/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1105, in create_thread
    name=f.__name__,
AttributeError: 'NoneType' object has no attribute '__name__'
```

Do you have an idea where this comes from? If you cannot make a quick guess then please don't bother digging too deep until the next person comes upon this issue. I start thinking my NAS is the root of the problems as I had lots of errors running an updated version of webtools about 1.5 years ago and now experience random crashes of my NAS when playing media (you have seen my issue in the forums 4 days ago and applied the correct label).

Maybe when I have time I should backup everything and reinstall the whole plex-system to see if that solves some problems.

Logs of exporttools are [here](https://github.com/ukdtom/ExportTools.bundle/files/3511299/PMS.Plugin.Logs.zip), let me know if you want to have PMS-logs as well.

**Comment by rabelux** [comment]
One question about the sentence "Please fill out the information requested on the issue report page" mentioned on the wikipage [Trouble Shooting](https://github.com/ukdtom/ExportTools.bundle/wiki/Trouble-Shooting):
I could not find any requested information, did I miss something or was that sentence copied from another wiki?

**Comment by ukdtom** [comment]
I noticed in the logs, that you did a major upgrade on ExportTools from a very old one to the latest
Looks like something in the process made your current settings invalid, so we need to nuke them and completely reset the plugin

I wrote howto for WebTools, but it's the same procedure, just replace the WebTools name with ExportTools 

https://github.com/ukdtom/WebTools.bundle/wiki/Reset#manually

After that, restart PMS, and please report back

And yes, template was copied, so will look into that, thanks

**Comment by rabelux** [comment]
It worked, thanks!
