### ISSUE TITLE
New Audio Level for Albums/Books only

### ISSUE THREAD

**Issue by Supertramp78** [ukdtom/ExportTools.bundle#112]
All existing Audio export settings are at the track level since so much data (bit rate, etc) is at that level. 
What I'm looking for is an export of just the albums and album artists. This would be to generate a list of albums in your library or books in your audio book library. 
The question would be is there any album level data IN PLEX? Or is it all stored at the track level? Or if an album is in there with multiple album artists, would it be in the export twice? The answer would be yes. By my understanding you only have one album artist per album and that may be "Various" but each track can have a different Artist. This is why this export should probably leave Artist off and focus on Album artist.
I don't know what other metadata is available at the ALBUM level in PLEX that you can export but if it is just a list of artists and their albums, that would be great.

**Comment by ukdtom** [comment]
Note to self:

Call would be: `/library/sections/X/all?type=9`

Must use paging, and avail fields are:
* ratingKey  (Mandatory)
* studio
* parentTitle (The artist)
* summary
* year
* addedAt
* originallyAvailableAt
* lastViewedAt
* thumb
* art
* parentThumb
* updatedAt
* deepAnalysisVersion
* Genre (Can be multiple)

**Comment by ukdtom** [comment]
Irrelevant, due to
[WebTools-NG](https://forums.plex.tv/t/webtools-ng/598539)
