### ISSUE TITLE
No Libraries listed

### ISSUE THREAD

**Issue by peterlaws** [ukdtom/ExportTools.bundle#117]
I'm not getting any libraries listed upon selecting Reload Library list, save, then re-open.

I still see Idle and Reload Library list......

Plex Version 4.18.1
ET Version 2.0.0.7

**Comment by ukdtom** [comment]
Logs please, and in a zip

**Comment by peterlaws** [comment]
Which logs?

**Comment by ukdtom** [comment]
ET logs

https://github.com/ukdtom/ExportTools.bundle/wiki/Trouble-Shooting

**Comment by peterlaws** [comment]
Was a folder owner issue...

When I refresh, now I get a 'There was a problem saving these settings.', which is another permission error with my drive mounts:

> OSError: [Errno 13] Permission denied: '/mycloud2/Movies/ExportTools'

As they are mounts from a NAS, I'm unable to chown

**Comment by peterlaws** [comment]
By the way, Plex is on a Pi 3B

**Comment by ukdtom** [comment]
Sounds like you left the output dir as the default....

Specify one, and make sure to uncheck the ckeckbox below it in the prefs

Ref: https://github.com/ukdtom/ExportTools.bundle/wiki/Configuration#export-path

**Comment by peterlaws** [comment]
I never read............ The checkbox was the issue....... Thanks.
