### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by El-Snob** [ukdtom/ExportTools.bundle#122]
I try to export all the moves that are in my plex, to test it I started with a small Library with 8 movies.
It creates the "....-Wait-Please" file but nothing more. I tested it with several levels . Level 1 i started the export but after 3 Days there were just these wait files.

I also tried it in the Plex Web app and the URL.

Plex is installed on a Qnap TS-453B with 4 GB Ram.

Hope someone can help me.

**Comment by ukdtom** [comment]
I need the ExportTools logs in a zip

**Comment by El-Snob** [comment]
Thanks for your help.

[ExportTools.zip](https://github.com/ukdtom/ExportTools.bundle/files/4344066/ExportTools.zip)

**Comment by ukdtom** [comment]
From the logs, it looks like LineWrap is enabled, but set to a lenght of "-"

If so, set to 40 instead, and save, then try again

**Comment by El-Snob** [comment]
I've changed that but its still the same result.

[ExportTools.zip](https://github.com/ukdtom/ExportTools.bundle/files/4347695/ExportTools.zip)

**Comment by ukdtom** [comment]
Sadly, I can't reproduce, so I suspect it's a problem in your database, that ET chokes on.

If you are willing to upload a copy of your database to like dropbox, and then DM me in the Plex forums with the location, I'll take a look

**Comment by ukdtom** [comment]
Closed due to lack of response
