### ISSUE TITLE
Use ExportTools on NAS Synology

### ISSUE THREAD

**Issue by Al4ndil** [ukdtom/ExportTools.bundle#123]
Hi,

I need help to use ExportTools. My plex installed on a NAS Synology with Docker.

I succeeded to install WebTools and ExportTools and i configured permissions on the export path. But i have always this issue : 
<Response code="2000" status="IndexError: list index out of range">
<Traceback>
Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-e106a8a91/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/config/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 70, in launch playlist=playlist) File "/config/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 69, in getOutFileName './/Directory[@title="' + title + '"]')[0] File "/usr/lib/plexmediaserver/Resources/Plug-ins-e106a8a91/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda> _getitem_ = lambda x, y: x.__getitem__(y), IndexError: list index out of range
</Traceback>
</Response>

Thx for your help

**Comment by ukdtom** [comment]
I need a zip with all ET logs, not just a snip

**Comment by Al4ndil** [comment]
Et voilà !

[Logs.zip](https://github.com/ukdtom/ExportTools.bundle/files/4399336/Logs.zip)

**Comment by ukdtom** [comment]
Try and launch it with an url like 

`http://IP_OF_SERVER:32400/applications/ExportTools/launch?title=Animations%20-%20Astrix&playlist=false&X-Plex-Token=Plex-Token-Here`

**Comment by Al4ndil** [comment]
Same thing....
[Logs.zip](https://github.com/ukdtom/ExportTools.bundle/files/4399447/Logs.zip)

**Comment by ukdtom** [comment]
Before we go any further, does it work when launched from preferences instead?

**Comment by ukdtom** [comment]
And logs showed, that I got the title of your library wrong ;)

Isn't it: `Animations - Astrix` ?

**Comment by Al4ndil** [comment]
Animations - Astérix in ASCII... that's it my problem ? :$

**Comment by ukdtom** [comment]
Yes, you need to URL Encode it as said in the Wiki!

So your title will be: Animations%20-%20Ast%C3%A9rix

**Comment by Al4ndil** [comment]
Hi,
I had already used this url ... And i have this error : 
Response code="2000" status="ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters"

**Comment by ukdtom** [comment]
So, as asked, does it work if launching from the preferences?

**Comment by Al4ndil** [comment]
where is this access ? i didn't see a direct access

**Comment by ukdtom** [comment]
https://github.com/ukdtom/ExportTools.bundle/wiki/IMPORTANT-NOTICE

**Comment by Al4ndil** [comment]
Ok i understand but now, i think i don't have the good export path. How to configure that with plex on Docker ? A path in the ExportTools path ?

**Comment by ukdtom** [comment]
You need some directory, that the plex user has full rights to, and then configure it like
`/volume1/SomePath` or you could simply let ET use autopath

Please read the manual
https://github.com/ukdtom/ExportTools.bundle/wiki/Configuration#export-path

**Comment by Al4ndil** [comment]
It's work. My bad ... Very sorry !
