### ISSUE TITLE
Export Tools Freezing Up

### ISSUE THREAD

**Issue by Gus019** [ukdtom/ExportTools.bundle#124]
After originally installing, I was able to generate both the xlsx and csv files, however recently I've noted the creation of these files would freeze up. After opening the ExportTools folder, I was able to see the file count increase as the xlsx or csv files were being created, but then at a certain point, the file count would stop and nothing else would happen. This would happen when I would create a list for both my movies and tv shows folder. Though it would not happen with the 4K movies folder, albeit that folder is much smaller than the other two. While reviewing the ExportTools log, I honestly can't determine what is going on and am looking for assistance to determine the problem.

I basically just want to create a list of all my shows/movies as I have been going through all of them to make sure they are optimized for remote access, converting files to a Mp4/H.264

Attached is the ExportTools log. If another log is needed like the PMS log, let me know.
[com.plexapp.plugins.ExportTools.log](https://github.com/ukdtom/ExportTools.bundle/files/4464870/com.plexapp.plugins.ExportTools.log)

I am also running this on a QNAP TS-451 451+ with 16gb RAM.

**Comment by ukdtom** [comment]
Could I get a zip of all the ET logs please

**Comment by ukdtom** [comment]
And PMS logs as well

**Comment by Gus019** [comment]
[PMS Logs.zip](https://github.com/ukdtom/ExportTools.bundle/files/4465290/PMS.Logs.zip)
Attached are all of the PMS and PMS Plugin Logs

**Comment by ukdtom** [comment]
Hmmm.....I've asked Plex if they changed something in PMS lately, since it looks like PMS is killing ET after about 30 min :(

Workaround for you is this:
https://forums.plex.tv/t/rel-exporttools/175915/508?u=dane22

**Comment by Gus019** [comment]
Thanks for the response! I'll try the workaround. Great work with the plugin, can't say enough how much I appreciate the tool!
