### ISSUE TITLE
TV Series Export - Audio Title

### ISSUE THREAD

**Issue by cybergrimes** [ukdtom/ExportTools.bundle#129]
Hi there, I've been using your great export tool for awhile trying to get some uniformity on my movie rips. I often refer to 'Audio Title' from the movie library export but it does not appear to be available in the TV series export at any level. It's a level 3 item for movies. Could it be added to TV?

Thanks!

**Comment by ukdtom** [comment]
Never had an episode with that filled out, so could you provide an xml of an episode, that has a title for the audio track

**Comment by cybergrimes** [comment]
It will not allow me to attach an XML so I've output the MediaInfo as text.
This is from an episode of Star Trek TNG ripped from Blu-ray disc.

<Title>Surround 7.1</Title>

[mediainfo.txt](https://github.com/ukdtom/ExportTools.bundle/files/4658398/mediainfo.txt)

**Comment by ukdtom** [comment]
Sorry, but I need the XML, since I need the XPATH in it to the element

So provide it elsewhere

**Comment by cybergrimes** [comment]
Here's a OneDrive link
https://1drv.ms/u/s!AuhKYK_kzKw6ibRtAuJ5VKgsREHf8g?e=5XWPsk

Thanks for looking at this

**Comment by cybergrimes** [comment]
Sorry again, it just occurred to me you probably wanted the Plex XML, not MediaInfo XML
Here'a OneDrive link for that instead
https://1drv.ms/u/s!AuhKYK_kzKw6ibRusbfFL5k6XcrlAw?e=jeJsxg

**Comment by ukdtom** [comment]
Thanks, and yes, it was the PMS xml I wanted ;)

All good, and looking into it

**Comment by ukdtom** [comment]
Also missing displayTitle of the Audio Stream

**Comment by ukdtom** [comment]
Please try this one, and report back both good and bad

https://github.com/ukdtom/ExportTools.bundle/archive/tommy-work.zip

You need shows in level 6 as a minimum

**Comment by ukdtom** [comment]
Note to self, remember Wiki update

**Comment by cybergrimes** [comment]
This looks great. Nothing bad jumps out at me.
I pulled it into Access, queried to see if all the titles lined up with the audio channels. Everything is lined up correctly, title missing from certain files as expected.

**Comment by ukdtom** [comment]
Cool, and thanks.

Will be in the next release
