### ISSUE TITLE
I wanna develop the plugin for plex

### ISSUE THREAD

**Issue by impossible98** [ukdtom/ExportTools.bundle#141]
Where can I find the docs for developing the plugin? I have found my websites and forum. Thanks you give the urls.

**Comment by ukdtom** [comment]
Huh, what do you mean?

**Comment by impossible98** [comment]
@ukdtom the documentation of how to write the plugin
the plugin folder how to name
the main code how to name

**Comment by ukdtom** [comment]
But....This is a plugin, not the docs to develop!

If you want to develop a plugin, then note that they are been phased out by Plex, so don't start on it, and for docs, search the Plex Forums
