### ISSUE TITLE
Guid broken with new movie agent

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/ExportTools.bundle#143]
We need to look into this asap

**Comment by ukdtom** [comment]
Note to self:

Under media

`
<Guid id="imdb://ttxxttzz"/>
<Guid id="tmdb://xxyy"/>
`

Origen guid now looks like:

`
guid="plex://movie/something"
`

**Comment by ukdtom** [comment]
This will not be fixed, but instead added to a soon to be released product ;)

**Comment by NostalgicStone** [comment]
What kind of timeline you thinking on this upcoming product, and price? I have some BAT to send your way if soon 👍

**Comment by ukdtom** [comment]
We expect to open up for translators and Alpha tester by the end of this month.

And Pricewise, well, if we ever meet in real life, you own me a beer ;)

**Comment by 7171TBJ** [comment]
It is possible to test it yet?

**Comment by ukdtom** [comment]
Yes, but not with ExportTools.

See: https://forums.plex.tv/t/alpha-testing-webtools-ng/598539

**Comment by ukdtom** [comment]
Changed my mind, since WT-NG is delayed ;)

**Comment by NostalgicStone** [comment]
LOL
How's the progress going?

**Comment by ukdtom** [comment]
Slowly, and completely sidetracked with real work as well :(

So Hobby is sadly 2nd priority

**Comment by NostalgicStone** [comment]
Sorry to hear that.

**Comment by ukdtom** [comment]
When released, this fix will be in V2.0.0.13
