### ISSUE TITLE
Can't get concurrent URL scans

### ISSUE THREAD

**Issue by MarcosBL** [ukdtom/ExportTools.bundle#145]
I'm trying to get this working for automatic collections backup https://github.com/ukdtom/ExportTools.bundle/wiki/Use-a-URL-to-launch-ExportTools

After configuring __ExportTools.bundle__ I have setup a simple bash script that will call the URL secuencially, just changing the collections (4 of them):

````
# cat /root/scripts/plexsave
curl "http://192.168.1.50:32400/applications/ExportTools/launch?title=MEDIA%20-%20Peliculas&level=Level%202&skipts=True&X-Plex-Token=REDACTED"
curl "http://192.168.1.50:32400/applications/ExportTools/launch?title=MEDIA%20-%20Series&level=Level%202&skipts=True&X-Plex-Token=REDACTED"
curl "http://192.168.1.50:32400/applications/ExportTools/launch?title=NENAS%20-%20Series&level=Level%202&skipts=True&X-Plex-Token=REDACTED"
curl "http://192.168.1.50:32400/applications/ExportTools/launch?title=NENAS%20-%20Peliculas&level=Level%202&skipts=True&X-Plex-Token=REDACTED"
````

* If I launch every line one by one, waiting for the export file to appear in the folder, everything works as expected.
* But if  Ilaunch the script (or 2 of its lines fast, one after the other), **only the latest one** finishes, all others die leaving the temp files `*.tmp-Wait-Please` in place
* As I can't know how much time it will take for each collection to export, is hard to get a script running that could save all your collections.

It's something easily fixable ? Maybe some lock filename that could be changed per run ? or something like that ?

Thanks for such a great plugin !

**Comment by ukdtom** [comment]
This is wad, and will not be fixed, since dev work on this plugin er close to EOL, due to: https://github.com/WebTools-NG/WebTools-NG
