### ISSUE TITLE
What is it that makes Exporttools show up as a plugin on my PLEX server?

### ISSUE THREAD

**Issue by Sorentoman** [ukdtom/ExportTools.bundle#148]
I have the bundle copied to the destination in instructions but then the documentation doesn't refer on how to add it to PLEX. The next instruction is "To configure this plugin, click on the little gear icon on top right, after launching the plugin." What gear icon, after launching, how can I launch something that isn't even configured. Cannot find any additional documentation on this tool on how to use. Any help would be appreciated.

**Comment by ukdtom** [comment]
https://github.com/ukdtom/ExportTools.bundle/wiki/IMPORTANT-NOTICE

**Comment by Sorentoman** [comment]
Not helpful. I assumed after I placed the Export Tools bundle in the directory specified that a reboot of the plex server would show the plug-in. It did not, any help would be greatly appreciated.

**Comment by ukdtom** [comment]
If it's not showing in the WebClient under `Settings/Manage/Plugins` then you most likely have a bad install

As such, more info is needed, like OS, install path etc.

**Comment by Sorentoman** [comment]
Okay let's see what I can provide you. First I have a Raspberry Pi 4 running the lastest version of Pi OS. The install path is /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/ExportTools.bundle. Your comment made me curious as to what permissions I had and saw that they were some set to "nobody" on execute. Changed them to everyone, rebooted server and now the plug-in shows up. Excellent, thanks for giving me some ideas on what to check. Now I get to see if I can get some output.

**Comment by Sorentoman** [comment]
Confused Again! Clicked gear icon and selected 'Reload Library List' and clicked SAVE. When I go back to settings I still do not see my libraries. Any ideas on what I am doing wrong.

**Comment by ukdtom** [comment]
First of all, your install dir for the plugins are wrong!
(And since not a RasPi dude, no idea about the correct path, but it's 4 sure not one with `-d87012962` in it)

Secondly, the user running PMS, must have full rights to the `Contents/DefaultPrefs.json` file

**Comment by ukdtom** [comment]
https://support.plex.tv/articles/201106098-how-do-i-find-the-plug-ins-folder/

**Comment by Sorentoman** [comment]
I see what your saying. There is another set of PMS folders under /var. Unfortunately for me is that I haven't enough experience copying folders from location to another in Linux and I cannot find a way to run the file manager in Admin mode which means I get permission denied. If I navigate to the destination folder in Debian. How can I copy files to it without putting in a destination in the command. EG. pi@plex-server:/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins $
is the destination. pi@plex-server:/usr/lib/plexmediaserver/Resources/Plug-ins-d87012962 $ is where the folder is I want to move. Gets so confusing when your are dealing with caps and spaces.

**Comment by ukdtom** [comment]
https://shapeshed.com/unix-mv/#how-to-move-a-directory

And not related to my plugin, so please seek platform help on a related platform fora, or google

**Comment by Sorentoman** [comment]
Thanks for assistance, is there not others here that are more familiar with platform.

**Comment by ukdtom** [comment]
Nope, not here.....
This is a pure dev thing, between users and me, one-2-one

For community support, use the forum thread for ExportTools, as outlined in the wiki, but as already said, your problem is not related to my plugin, but to general Linux usage, so try the RasPi forums, if such a thing exists

**Comment by Sorentoman** [comment]
Nevermind, finally got it to work. Thanks, your assistance was very helpful. Seems strange going back to command prompts, lived and breathed it in the DOS world back in the 80's.
