### ISSUE TITLE
Export TV Show Original Added Date when using Shows Only Levels

### ISSUE THREAD

**Issue by talos5** [ukdtom/ExportTools.bundle#149]
As it says. I'm copying specific simple columns of data out of ET to keep a spreadsheet of my library for my friends to access. I need to be able to sort TV shows from when they are first added, not episodes. Thanks!

**Comment by ukdtom** [comment]
https://github.com/ukdtom/ExportTools.bundle/wiki/TV-Series-Export-Level#level-2

**Comment by ukdtom** [comment]
Sorry, but what on earth do you mean?

Exporting Shows Only Level 2 should give you that

https://github.com/ukdtom/ExportTools.bundle/wiki/TV-Series-Export-Level#level-2

**Comment by talos5** [comment]
Sorry, I was trying to think of the best way to write it and it wasn't very clear. 

Shows Only 2 has:

Show Only 2 (All of Show 1, as well as fields below)

    Directors
    Writers
    Roles
    Genres

I didn't need when an episode was added, but when the TV series as a whole was first added to Plex for sorting, since I highlight new additions.

**Comment by ukdtom** [comment]
Got It ;)

**Comment by ukdtom** [comment]
When released, this fix will be in V2.0.0.13
