### ISSUE TITLE
Configuration instructions are not clear

### ISSUE THREAD

**Issue by vanowm** [ukdtom/ExportTools.bundle#15]
> When this channel is launched the first time, it'll default to put the exported file in the same directory as the library you are trying to export.

Database file of the library? Where is the library located?
I don't know how plex works, but because a library can contain multiple folders, for me library is a virtual terminology it doesn't have physical appearance on my system.

Very unclear instructions.

**Comment by ukdtom** [comment]
Altered https://github.com/ukdtom/ExportTools.bundle/wiki/Configuration
