### ISSUE TITLE
Exporting TV Show Season Posters

### ISSUE THREAD

**Issue by TimmyTwoHatsTTV** [ukdtom/ExportTools.bundle#157]
I have used this export plugin for movies and it worked perfectly. When I use it for TV Shows I either select "Show Only Level 3" in which case it just grabs the TV Show poster and nothing else. or I select "Level 3" where it grabs the TV Show poster and all of the episode thumbnails. However, neither option actually grab the posters for the seasons of the tv shows. How can this be achieved?

**Comment by ukdtom** [comment]
Exporting posters are not supported for "Show Only" levels

**Comment by TimmyTwoHatsTTV** [comment]
Okay, it did grab the TV Show posters though. 
Is there any option I can select to export the Posters for the TV Show and it's seasons?

**Comment by ukdtom** [comment]
Not with ExportTools.

As said, not supported
