### ISSUE TITLE
How to export TV Show Season Posters?

### ISSUE THREAD

**Issue by TimmyTwoHatsTTV** [ukdtom/ExportTools.bundle#158]
What settings do I need to select to export TV Show poster along with their Season Posters as well?

**Comment by ukdtom** [comment]
Ref: https://github.com/ukdtom/ExportTools.bundle/issues/157

STOP opening new issues for this!

It's not supported, and never will be!

**Comment by TimmyTwoHatsTTV** [comment]
Initially you only said it wasn’t supposed specifically through “Show Only
Levels” not that export tools didn’t support the feature. You then
prematurely closed the thread so I couldn’t reply. Hence why I created the
second thread and only then did you actually answer my question.
Next time be more thorough
