### ISSUE TITLE
[REQ] let user select what data they want to export

### ISSUE THREAD

**Issue by vanowm** [ukdtom/ExportTools.bundle#16]
It would be nice if we could select what fields we want to export instead of level of bundles.

Thank you.

**Comment by ukdtom** [comment]
Indeed, but the Plex FrameWork is too limited to create such a prefs screen

**Comment by vanowm** [comment]
No checkboxes available or lists ?

**Comment by ukdtom** [comment]
Too crowded for this, since the prefs module req. it all to be on the same page :-(

Future though, and no ETA here, is for it to merge into WebTools, and when so, it's a completely new ballgame
