### ISSUE TITLE
One playlist does not export

### ISSUE THREAD

**Issue by frankusb** [ukdtom/ExportTools.bundle#161]
I have 3 playlists: one manual playlist with 501 songs, one smart playlist with 740 songs and one smart playlist with 19880 songs. The first two playlists export just fine but the smart playlist with 19880 songs does not export. I don't see any indication that anything happened. Is there a place I can look to see what's happening?

**Comment by ukdtom** [comment]
Log file would be a good start ;)

**Comment by frankusb** [comment]
Enabled logging, exported one working and one non working playlist. I downloaded the logs, where should I be looking?

**Comment by frankusb** [comment]
Looks reasonable.

Jan 27, 2021 08:12:52.903 [0x7f30c3346700] DEBUG - [com.plexapp.plugins.ExportTools] HTTP reply status 200, with 0 bytes of content.
Jan 27, 2021 08:12:52.903 [0x7f315dffb700] DEBUG - Completed: [127.0.0.1:54996] 200 GET /:/plugins/com.plexapp.plugins.ExportTools/prefs/set?Libraries=&Playlists= (12 live) GZIP 4ms 293 bytes
Jan 27, 2021 08:12:52.914 [0x7f30fd7fa700] DEBUG - Request: [127.0.0.1:55002 (Loopback)] GET /playlists (12 live) GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:52.916 [0x7f315dffb700] DEBUG - Completed: [127.0.0.1:55002] 200 GET /playlists (12 live) GZIP 1ms 821 bytes
Jan 27, 2021 08:12:52.920 [0x7f30c4348700] DEBUG - HTTP 200 response from GET http://127.0.0.1:42599/applications/ExportTools/:/prefs/set?Playlists=2
Jan 27, 2021 08:12:52.920 [0x7f30c4348700] DEBUG - [com.plexapp.plugins.ExportTools] HTTP reply status 200, with 0 bytes of content.
Jan 27, 2021 08:12:52.921 [0x7f315dffb700] DEBUG - Completed: [192.168.1.132:62149] 200 GET /applications/ExportTools/:/prefs/set?Playlists=2 (11 live) TLS GZIP 35ms 993 bytes (pipelined: 16)
Jan 27, 2021 08:12:52.936 [0x7f30cffff700] DEBUG - Request: [127.0.0.1:55004 (Loopback)] GET /playlists/73510/items (12 live) GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:54.813 [0x7f30cffff700] DEBUG - It took 1750.000000 ms to retrieve 19880 items.
Jan 27, 2021 08:12:54.993 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:12:54.993 [0x7f315dffb700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:12:54.993 [0x7f30fd7fa700] DEBUG - Request: [192.168.1.132:62149 (Subnet)] GET /:/prefs (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:54.993 [0x7f30c3346700] DEBUG - Request: [192.168.1.132:62141 (Subnet)] GET /accounts/1 (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:54.994 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:12:54.994 [0x7f30c3346700] DEBUG - Request: [192.168.1.132:62163 (Subnet)] GET /myplex/account (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:54.994 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:12:54.994 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62141] 200 GET /accounts/1 (12 live) TLS GZIP 0ms 598 bytes (pipelined: 22)
Jan 27, 2021 08:12:54.994 [0x7f30c3346700] DEBUG - Request: [192.168.1.132:62164 (Subnet)] GET /system/:/prefs (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:54.994 [0x7f30c3346700] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/:/prefs
Jan 27, 2021 08:12:54.994 [0x7f30c3346700] DEBUG - HTTP requesting GET http://127.0.0.1:39199/system/:/prefs
Jan 27, 2021 08:12:54.995 [0x7f315dffb700] DEBUG - Completed: [192.168.1.132:62163] 200 GET /myplex/account (12 live) TLS GZIP 0ms 3220 bytes (pipelined: 13)
Jan 27, 2021 08:12:54.997 [0x7f315dffb700] DEBUG - Completed: [192.168.1.132:62149] 200 GET /:/prefs (12 live) TLS GZIP 3ms 8280 bytes (pipelined: 17)
Jan 27, 2021 08:12:54.999 [0x7f30c3346700] DEBUG - HTTP 200 response from GET http://127.0.0.1:39199/system/:/prefs
Jan 27, 2021 08:12:54.999 [0x7f30c3346700] DEBUG - [com.plexapp.system] HTTP reply status 200, with 418 bytes of content.
Jan 27, 2021 08:12:54.999 [0x7f315dffb700] DEBUG - Completed: [192.168.1.132:62164] 200 GET /system/:/prefs (12 live) TLS GZIP 5ms 813 bytes (pipelined: 17)
Jan 27, 2021 08:12:55.021 [0x7f315dffb700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:12:55.021 [0x7f30c4348700] DEBUG - Request: [192.168.1.132:62192 (Subnet)] GET /:/websockets/notifications?filters=log (13 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:55.021 [0x7f30c4348700] DEBUG - WebSocket: Performing handshake from origin https://app.plex.tv
Jan 27, 2021 08:12:55.021 [0x7f30c4348700] DEBUG - Beginning read from WebSocket
Jan 27, 2021 08:12:55.028 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:12:55.028 [0x7f30fd7fa700] DEBUG - Request: [192.168.1.132:62164 (Subnet)] GET /activities (13 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:12:55.028 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62164] 200 GET /activities (13 live) TLS GZIP 0ms 429 bytes (pipelined: 18)
Jan 27, 2021 08:12:56.260 [0x7f315e7fc700] DEBUG - Completed: [127.0.0.1:55004] 200 GET /playlists/73510/items (13 live) GZIP 3324ms 1848347 bytes

But no file output.

Jan 27, 2021 08:13:28.333 [0x7f30cffff700] DEBUG - [com.plexapp.plugins.ExportTools] HTTP reply status 200, with 0 bytes of content.
Jan 27, 2021 08:13:28.333 [0x7f315e7fc700] DEBUG - Completed: [127.0.0.1:55022] 200 GET /:/plugins/com.plexapp.plugins.ExportTools/prefs/set?Libraries=&Playlists= (12 live) GZIP 3ms 293 bytes
Jan 27, 2021 08:13:28.335 [0x7f30cffff700] DEBUG - Request: [127.0.0.1:55028 (Loopback)] GET /playlists (12 live) GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:28.337 [0x7f315e7fc700] DEBUG - Completed: [127.0.0.1:55028] 200 GET /playlists (12 live) GZIP 1ms 821 bytes
Jan 27, 2021 08:13:28.341 [0x7f30fd7fa700] DEBUG - HTTP 200 response from GET http://127.0.0.1:42599/applications/ExportTools/:/prefs/set?Playlists=3
Jan 27, 2021 08:13:28.341 [0x7f30fd7fa700] DEBUG - [com.plexapp.plugins.ExportTools] HTTP reply status 200, with 0 bytes of content.
Jan 27, 2021 08:13:28.341 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62199] 200 GET /applications/ExportTools/:/prefs/set?Playlists=3 (11 live) TLS GZIP 21ms 993 bytes (pipelined: 4)
Jan 27, 2021 08:13:28.347 [0x7f30cffff700] DEBUG - Request: [127.0.0.1:55030 (Loopback)] GET /playlists/88784/items (12 live) GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:28.437 [0x7f30cffff700] DEBUG - It took 60.000000 ms to retrieve 740 items.
Jan 27, 2021 08:13:28.487 [0x7f315e7fc700] DEBUG - Completed: [127.0.0.1:55030] 200 GET /playlists/88784/items (12 live) GZIP 140ms 75434 bytes
Jan 27, 2021 08:13:28.572 [0x7f30fd7fa700] DEBUG - Request: [127.0.0.1:55032 (Loopback)] GET /playlists/88784/items (12 live) Page 0--1 GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:28.577 [0x7f30fd7fa700] DEBUG - Setting container serialization range to [0, -1] (total=-1)
Jan 27, 2021 08:13:28.654 [0x7f315e7fc700] DEBUG - Completed: [127.0.0.1:55032] 200 GET /playlists/88784/items (12 live) GZIP Page 0--1 82ms 556 bytes
Jan 27, 2021 08:13:28.657 [0x7f30cffff700] DEBUG - Request: [127.0.0.1:55034 (Loopback)] GET /playlists/88784/items (12 live) GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:28.741 [0x7f30cffff700] DEBUG - It took 60.000000 ms to retrieve 740 items.
Jan 27, 2021 08:13:28.757 [0x7f315dffb700] DEBUG - Completed: [192.168.1.132:62147] 200 GET /player/proxy/poll?deviceClass=pc&protocolVersion=3&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1 (12 live) TLS GZIP 20000ms 5 bytes (pipelined: 8)
Jan 27, 2021 08:13:28.763 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:28.763 [0x7f30fd7fa700] DEBUG - Request: [192.168.1.132:62147 (Subnet)] GET /player/proxy/poll?deviceClass=pc&protocolVersion=3&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1 (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:28.763 [0x7f30fd7fa700] DEBUG - Content-Length is -1 (of total: -1).
Jan 27, 2021 08:13:28.791 [0x7f315e7fc700] DEBUG - Completed: [127.0.0.1:55034] 200 GET /playlists/88784/items (12 live) GZIP 134ms 75434 bytes
Jan 27, 2021 08:13:30.562 [0x7f315dffb700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:30.563 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:30.563 [0x7f30fd7fa700] DEBUG - Request: [192.168.1.132:62199 (Subnet)] GET /:/prefs (11 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:30.563 [0x7f30cffff700] DEBUG - Request: [192.168.1.132:62198 (Subnet)] GET /accounts/1 (11 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:30.563 [0x7f315dffb700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:30.564 [0x7f315e7fc700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:30.564 [0x7f30c4348700] DEBUG - Request: [192.168.1.132:62196 (Subnet)] GET /myplex/account (11 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:30.564 [0x7f30c3346700] DEBUG - Request: [192.168.1.132:62197 (Subnet)] GET /system/:/prefs (11 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:30.564 [0x7f30c3346700] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/:/prefs
Jan 27, 2021 08:13:30.565 [0x7f30c3346700] DEBUG - HTTP requesting GET http://127.0.0.1:39199/system/:/prefs
Jan 27, 2021 08:13:30.565 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62198] 200 GET /accounts/1 (11 live) TLS GZIP 2ms 598 bytes (pipelined: 2)
Jan 27, 2021 08:13:30.566 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62196] 200 GET /myplex/account (11 live) TLS GZIP 3ms 3220 bytes (pipelined: 2)
Jan 27, 2021 08:13:30.569 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62199] 200 GET /:/prefs (11 live) TLS GZIP 6ms 8280 bytes (pipelined: 5)
Jan 27, 2021 08:13:30.571 [0x7f30c3346700] DEBUG - HTTP 200 response from GET http://127.0.0.1:39199/system/:/prefs
Jan 27, 2021 08:13:30.571 [0x7f30c3346700] DEBUG - [com.plexapp.system] HTTP reply status 200, with 418 bytes of content.
Jan 27, 2021 08:13:30.571 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62197] 200 GET /system/:/prefs (11 live) TLS GZIP 7ms 813 bytes (pipelined: 2)
Jan 27, 2021 08:13:30.617 [0x7f315dffb700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:30.618 [0x7f30c4348700] DEBUG - Request: [192.168.1.132:62203 (Subnet)] GET /:/websockets/notifications?filters=log (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:30.618 [0x7f30c4348700] DEBUG - WebSocket: Performing handshake from origin https://app.plex.tv
Jan 27, 2021 08:13:30.618 [0x7f30c4348700] DEBUG - Beginning read from WebSocket
Jan 27, 2021 08:13:30.642 [0x7f315dffb700] DEBUG - Auth: authenticated user 1 as frankusb
Jan 27, 2021 08:13:30.642 [0x7f30cffff700] DEBUG - Request: [192.168.1.132:62197 (Subnet)] GET /activities (12 live) TLS GZIP Signed-in Token (frankusb)
Jan 27, 2021 08:13:30.643 [0x7f315e7fc700] DEBUG - Completed: [192.168.1.132:62197] 200 GET /activities (12 live) TLS GZIP 1ms 429 bytes (pipelined: 3)

This results in two files.

'Playlist-Christmas Music-Simple-20210127-081328.csv'
'Playlist-Christmas Music-Simple-20210127-081328.m3u8'

**Comment by frankusb** [comment]
Here is more in case I missed something.

[Plex Media Server.log](https://github.com/ukdtom/ExportTools.bundle/files/5880881/Plex.Media.Server.log)

**Comment by ukdtom** [comment]
Wrong log, I need the ET log files in a zip

Ref: https://github.com/ukdtom/ExportTools.bundle/wiki/Trouble-Shooting

**Comment by frankusb** [comment]
Ah, thank you.
[com.plexapp.plugins.ExportTools.log](https://github.com/ukdtom/ExportTools.bundle/files/5883199/com.plexapp.plugins.ExportTools.log)

**Comment by ukdtom** [comment]
It's a bug:

`2021-01-27 08:35:53,178 (7fe8767fc700) :  DEBUG (__init__:782) - Section type is playlists
2021-01-27 08:35:53,178 (7fe8767fc700) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/playlists/73510/items'
2021-01-27 08:35:56,558 (7fe8767fc700) :  CRITICAL (__init__:828) - Exception happened in backgroundScanThread was (2103, 'Data of size 25740803 is greater than the maximum size 5242880')`

When said, involves changes that are not scheduled, since we are getting near EOL for ExportTools, and req a lot of changes codewise.

Sorry, and do keep an eye out for: https://github.com/WebTools-NG/WebTools-NG, that is slated to take over, but sadly not there yet
