### ISSUE TITLE
ExportTools doesn't create .m3u

### ISSUE THREAD

**Issue by jotade94** [ukdtom/ExportTools.bundle#163]
I'm using ExportTools V2.0.0.16 and I have managed to generate the .csv and .xlsx files from my collections.

<img src="https://preview.redd.it/7ycbzfrciua81.png?width=364&format=png&auto=webp&s=8f277d2a01234cbcf7bfdc4a70fc8f66cac4fd4a">

But I don't know where the .m3u files are saved, right now I have the configuration "create m3u8 playlist file" Enhanced
<img src="https://preview.redd.it/kaacw45uiua81.png?width=497&format=png&auto=webp&s=69e5994dac4bf9405e4790a0745cb58fa0fa0713">

**Comment by ukdtom** [comment]
Did you export a Playlist?
It's only when such an export is selected, that the .m3u file is generated

**Comment by jotade94** [comment]
> Did you export a Playlist? It's only when such an export is selected, that the .m3u file is generated

I tried to export a collection no a playlist, only work in playlist?

**Comment by ukdtom** [comment]
Yep
