### ISSUE TITLE
Add the Title value to the fields Sort title and Original Title when empty

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/ExportTools.bundle#36]
Would it be possible to add the **_Title_** value to the fields **_Sort title_** and **_Original Title_** when they don't have a value in the database instead of filling them with **_N/A_**?

No point in sorting a table in Excel based on the **_Sort title_** when most of the cells contain **_N/A_**. 

I do this manually today when I import the cvs file into Excel, but with 6100+ movies in my collection, it takes some time... ;-)

**Comment by ukdtom** [comment]
Good idea.
I'll see what I can do

**Comment by ukdtom** [comment]
Please check the Tommy Work branch, and report back both good and bad.

Check the changelog, as well as the Channel Prefs, that now have new settings

**Comment by SvenErik1968** [comment]
Perfect!

**Comment by ukdtom** [comment]
Thanks
