### ISSUE TITLE
Export of movie countries

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/ExportTools.bundle#40]
I notice that the export of a movie country is either a two letter country code or the country name, and two movies added at the same time and from the same country one could end up with the full name and the other with the country code. Here is the latest 18 movies added earlier today:

    US, France, US, US, FR, FR, CA, US, ES, DE, DE, US, US, US, DE, US, US, USA

So not sure if this is an issue with Plex or with ExportTools...

An image showing more examples: 

![snip_20171028221511](https://user-images.githubusercontent.com/10983802/32138126-01e2de96-bc2e-11e7-935c-9fea073f3737.png)

**Comment by ukdtom** [comment]
Since I export what PMS gives me, I can only assume it's a PMS bug.

So select info on a movie, and then "Show XML"

What's in there, is what I export

So what does that show?

**Comment by ukdtom** [comment]
And most likely related to metadata agents, during the import, or the info avail on the internet, that the agent downloads

**Comment by SvenErik1968** [comment]
The XML shows the same... So looks like an issue with the Plex Movie agent then. This was never an issue when I used The Movie Database agent.
Sorry to bother you on a Saturday evening!

**Comment by ukdtom** [comment]
NP, better with one too many, so this plugin can shine ;)
