### ISSUE TITLE
Playlists can not be exported when path is set to auto. You need to specify a manual path in the prefs

### ISSUE THREAD

**Issue by paran0ids** [ukdtom/ExportTools.bundle#58]
Path to export media changed to: d:\Export
Ignore export path and write output to the media storage instead unchecked, but still this Error ...

**Comment by paran0ids** [comment]
when option is unchecked, message: select preferences to set the export path
but path is already chosen with d:\Export

**Comment by ukdtom** [comment]
I need a zip with the logfiles for ExportTools, right after this happens.

**Comment by paran0ids** [comment]
where i can find the logfiles ?

**Comment by ukdtom** [comment]
https://github.com/ukdtom/ExportTools.bundle/wiki/Trouble-Shooting

**Comment by paran0ids** [comment]
Von: Tommy Mikkelsen <notifications@github.com> 
Gesendet: Montag, 26. März 2018 23:30
An: ukdtom/ExportTools.bundle <ExportTools.bundle@noreply.github.com>
Cc: paran0ids <xxx>; Author <author@noreply.github.com>
Betreff: Re: [ukdtom/ExportTools.bundle] Playlists can not be exported when path is set to auto. You need to specify a manual path in the prefs (#58)

 

https://github.com/ukdtom/ExportTools.bundle/wiki/Trouble-Shooting

—

**Comment by ukdtom** [comment]
So that means it works now, or?

and if still not working, I still need the logs!

**Comment by paran0ids** [comment]
I Sent them with E-Mail, i will sent tomorrow again.

**Comment by ukdtom** [comment]
Not send....Upload here, since doubt email attachments works with GitHub

**Comment by paran0ids** [comment]
[com.plexapp.plugins.ExportTools.log](https://github.com/ukdtom/ExportTools.bundle/files/1856238/com.plexapp.plugins.ExportTools.log)

**Comment by ukdtom** [comment]
Bad export path...

On a Syno, there's no d-drive!

Edit one of the libraries, and look at the path entered there to get an idea about what a path would look like.

And since I don't own a Syno, I've no clue, so if not working for you, you'll need to ask in the Plex Forums Synology

**Comment by paran0ids** [comment]
i have c-d-e-f drive and plex is on my Syno ;-) Even \\Synology\export is not accepted ...

**Comment by ukdtom** [comment]
Syno is LINUX

As such, you do not have c-d-e-f drive!

Those are mapped from windows or siml to a path on your Syno!

And as said...

Don't know valid path on syno, so please do as I said!

**Comment by trumpy81** [comment]
If you have ExportTools installed on the Synology NAS, along with Plex of course, then your saved path in ExportTools preferences MUST be a valid path on the NAS.

EG: /volume1/MyFolder is an example of a valid path on the Synology NAS.

Once the file has been saved, you can then use Windows to open the file from the location you selected using the UNC path by typing `\\DiskStation\MyFolder` into the address bar of your Windows File Explorer.

This assumes that MyFolder is a 'shared' folder on your NAS.

If you have a folder on the NAS 'mapped' to your Windows machine, then the file will appear in your 'mapped' drive letter location in Windows.

You MUST wait until ExportTools has finished writing to the file before you access it though.

**Comment by paran0ids** [comment]
thx trumpy81! You helped a lot, prob is solved, thx!
