### ISSUE TITLE
Windows - Excel error when opening ExportTools output file (xlsx).

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/ExportTools.bundle#60]
With ExportTools set to output level 666 and subsequently opening the .xlsx output file in Microsoft Excel, an error message is generated.

"We found a problem with some content in {filename}. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

Result after clicking on Yes:
![untitled-1](https://user-images.githubusercontent.com/12381786/38541233-c8f05afc-3ce1-11e8-9437-cf6454a4db0a.png)

Further error message displayed in .xml format:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error065360_01.xml</logFileName><summary>Errors were detected in file 'H:\Downloads\ExportTools\Movies-Level 666-20180410-152731.xlsx'</summary><removedRecords><removedRecord>Removed Records: Formula from /xl/worksheets/sheet1.xml part</removedRecord></removedRecords></recoveryLog>
```
ExportTool logs:
[ETlogs.zip](https://github.com/ukdtom/ExportTools.bundle/files/1893230/ETlogs.zip)

Plex version is 1.12.2.4929 running on Windows 10.

**Comment by ukdtom** [comment]
Hi Andy.

Works fine here for me, with LibreOffice.

Please update to the latest version of ExportTools, and try again, and if still failing, 
any chance you can PM me the output file, before Excel "Fixes" it?

And looks like a part entry that is broken, but latest version do handle part field differently, so...

**Comment by trumpy81** [comment]
Thanks Tommy.

I updated ExportTools and ran it again. I get the same error when opening the file in MS Excel.

I have provided the file, as ouput by ExportTools, and I have also included the ouput file after opening it and getting the error and then saved by MS Excel so that you can compare the raw output file against the modified saved file. I'm hoping that may offer a clue to the problem.

[ExportTools.zip](https://github.com/ukdtom/ExportTools.bundle/files/1896263/ExportTools.zip)

**Comment by ukdtom** [comment]
@trumpy81 

What happens if you export to csv, and open with Excel?

**Comment by trumpy81** [comment]
If I export to .csv and open it in MS Excel there are no errors or warnings.

I also noticed that the column spacing is uniform for all columns (quite narrow and does not display all characters in any column) when opening the .csv file.

When opening the .xlsx file the column spacing seems to be proportional to the maximum number of characters in each column.

Could it be the formula used for column spacing causing the error message in the .xlsx file?

**Comment by trumpy81** [comment]
I installed the updated ExportTools, but unfortunately, there is no change. I still recieve the same error message as before.

**Comment by ukdtom** [comment]
Darn
