### ISSUE TITLE
Cannot set Export path

### ISSUE THREAD

**Issue by roelvdh** [ukdtom/ExportTools.bundle#70]
I'm trying to set up ExportTools. I'm running Win10 while PMS version Version 1.13.0.5003 is on a Linux computer (CentOS).
As long as I check the box "Ignore export path and write output to the media storage instead" in Preferences, it all seems to work but I cannot find the results, which are probably hidden somewhere in /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/....
If I uncheck that box and give a custom export path in Windows, like C:\Users\Roel\Desktop\Plex.xlsx the program will not start and refers me back to Preferences for changing the Export Path. 
What am I doing wrong, or where can I find the results on my Linux machine?
Thanks for the help

**Comment by ukdtom** [comment]
The export path you specify is local to the PMS, in your case meaning your CentOS

So you need to create a directory named like `ExportTools` in like `/home`, and then grant rights to that directory to the user (plex) that runs your PMS

**Comment by roelvdh** [comment]
That makes sense, Tommy. Thanks a lot,
Roel

Op za 25 aug. 2018 om 00:16 schreef Tommy Mikkelsen <
notifications@github.com>:

**Comment by roelvdh** [comment]
This is a great tool that I will certainly be using a lot. For the current
moment, however, I am only looking for the file paths of all entries in the
PMS database, like File Explorer would do. I had hoped that "Title" would
mean "File Path" but obviously is doen't, and Level 666 seems quite over
the top. Is there a simple way to get a list of file paths using
ExportTools?

In case you might wonder why someone would ask this: My storage server was
damaged, the file system losing its superblock. I was able to restore most
of the contents but they are now enclosed in nameless directories. I need
to manually rename these directories according to the original structure.
Luckily I had a good backup of the PMS database. Now the challenge is to
obtain that structure and to reconnect the directories to their original
position in the file system.

Thanks in advance.

Kind regards, Roel



Op za 25 aug. 2018 om 12:21 schreef Tommy Mikkelsen <
notifications@github.com>:

**Comment by ukdtom** [comment]
Either Level 3 with the checkbox "Perform 'file present/accessibility' check. Requires more time. Useful when part of media file storage was accidentally lost" selected, or level 5 for movies

https://github.com/ukdtom/ExportTools.bundle/wiki/Movie-Export-Level

When that's said, might be faster to use WebTools with it's findmedia module!

https://github.com/ukdtom/WebTools.bundle/wiki/FindMedia
