### ISSUE TITLE
Auto Export Feature

### ISSUE THREAD

**Issue by ThePieMonster** [ukdtom/ExportTools.bundle#72]
Feature for setting up a scheduler that will run the export feature every day/week/year etc. 

Currently users having to login and manual kick off a export job. Instead users can setup a job to run, lets say every Sunday at 5am.

**Comment by ukdtom** [comment]
Due to the fact, that plugin's are EOL soon, I'll not invest time into this

**Comment by ThePieMonster** [comment]
> Due to the fact, that plugin's are EOL soon, I'll not invest time into this

I see here that they will continue to support plugins, but not the "Plex official" plugins. Is this what your referring too?
https://www.howtogeek.com/fyi/plex-is-killing-the-plugin-directory-heres-how-to-install-plugins-yourself/

**Comment by ukdtom** [comment]
Yes and no.

Step 1 is closure of the Official plugins.
Step 2 is removal of the framework => No more plugins
