### ISSUE TITLE
Cannot set export path

### ISSUE THREAD

**Issue by electricduck** [ukdtom/ExportTools.bundle#73]
The wiki tells me to deselect the option "Auto Select Export path to match the section exported", but after scrolling up and down on the settings panel for about 5 minutes, I am certain the option is not visible for me. Is the wiki out-of-date?

**Comment by ukdtom** [comment]
It's called `Ignore export path and write output to the media storage instead`

And yes, the Wiki was outdated, sorry about that...

And Wiki updated now thanks to your feedback, so huge thanks for spotting this
