### ISSUE TITLE
ExportTools Unable to Export to Directory

### ISSUE THREAD

**Issue by ghost** [ukdtom/ExportTools.bundle#77]
Hello,
I installed ExportTools [V1.0.2.16] and am unable to export to the downloads folder on my Mac. I wrote ~/Downloads in the “Path to export media to” field and also deselected the “Ignore export path and write output to the media storage instead”. However, the plugin is still telling me to “Select preferences to set the export path.” Not sure what the issue is. Any help would be appreciated. How do I give Plex permission to write to this folder as I think this may be the issue?
<img width="556" alt="screen shot 2019-02-08 at 15 24 58" src="https://user-images.githubusercontent.com/47462502/52505272-fa9bc480-2bb8-11e9-8b8a-821ff313943c.png">
<img width="334" alt="screen shot 2019-02-08 at 15 27 28" src="https://user-images.githubusercontent.com/47462502/52505273-fa9bc480-2bb8-11e9-9ddf-10a0137a202b.png">

**Comment by ukdtom** [comment]
Fixed by OP
https://forums.plex.tv/t/exporttools-unable-to-export-to-directory/373213/10?u=dane22
