### ISSUE TITLE
Export path problem - using Mac

### ISSUE THREAD

**Issue by ghost** [ukdtom/ExportTools.bundle#79]
I get “Select Preferences to set the export path”. Aaarrrgh!
I cut and pasted a path using Terminal but that didn't work.
I tried changing the Path to /Users/"username"/Desktop/Export as I saw in a posting here but it still didn't work.
I’m on a Mac running 10.14.3

**Comment by ukdtom** [comment]
Sorry, but not a MAC owner :(
All I can add here is, that the user running PMS must have R/W access to the directory you specify.

And if that's not it, I sadly can only suggest asking in the ExportTools thread in the forums, since I'm sure there's a lot of MAC users there
