### ISSUE TITLE
Roles field is broken for some Movies

### ISSUE THREAD

**Issue by JPB46** [ukdtom/ExportTools.bundle#80]
When I export Movies using Level 2, which includes the Roles field, some of the movies in my collection show actors that are correct but very obscure. As an example, the movie "**You Can't Take It with You (1938)**" shows _Alex Woloshin - Alice Keating - Almeda Fowler_ in the Roles column. When I previously ran this export (June 2018) it showed _Jean Arthur - Lionel Barrymore - James Stewart_, who are the primary actors. The list of actors for this movie on TMDb is very long; is this any part of the problem(?). Another example is **Casablanca (1942)** which now shows _Adolph Faylauer - Adrienne D'Ambricourt - Alberto Morin_, which should be _Humphrey Bogart - Ingrid Bergman - Paul Henreid_, from my previous listing.
I suspect this has to do with the current version of PMS (1.15.1.710) that I am running on my Windows 10 server. I am running ExportTools v 1.0.2.17 and was previously running 1.0.2.12. I can supply any needed info and logs, please advise.
Thank You in advance.

**Comment by ukdtom** [comment]
In the webclient, select one of the movies, then `Get Info` followed by `View XML`

Does it says the same as ExportTools?

**Comment by JPB46** [comment]
I would say no, the first 3 actors listed in the XML are the correct ones for the movie "You Can't Take It With You". The actors that ExportTools finds are there but way down in the Role ID listing. I have attached the zipped XML file for that movie so you can have a better look. 
Thank you for your quick response.
JPB46


[YouCantTake ItWithYou(20008).zip](https://github.com/ukdtom/ExportTools.bundle/files/2919798/YouCantTake.ItWithYou.20008.zip)

**Comment by ukdtom** [comment]
I need you to get the ExportTools logs as well, and an output file from ExportTools

**Comment by JPB46** [comment]
Logs and output file are attached...
[Movies-Level 2-20190228-131601.xlsx](https://github.com/ukdtom/ExportTools.bundle/files/2922751/Movies-Level.2-20190228-131601.xlsx)
[com.plexapp.plugins.ExportTools.log.zip](https://github.com/ukdtom/ExportTools.bundle/files/2922752/com.plexapp.plugins.ExportTools.log.zip)

**Comment by ukdtom** [comment]
Ahhh.......

Now I see it, and yes, I guess I should have explained that ;)

In Level 2, I don't grap extended info, but only limited.
If you want the full cast, then switch to level 3 or above, and they should be present.
Please confirm above, and I'll update the Wiki page [Movie Levels](https://github.com/ukdtom/ExportTools.bundle/wiki/Movie-Export-Level)

**Comment by JPB46** [comment]
Ok, yes the Level 3 option does list ALL the actors in the order shown in the XML for each movie. What I _wish_ is to have the Level 2 option display the FIRST 3 actors from the XML (as it did before), not the somewhat random listing it does now. I would be very willing to modify your code for testing, if that has any value to you.  Thank you for your input and time thus far.

**Comment by ukdtom** [comment]
That's sadly not going to happen, since that would req. me to do 2 call's against the PMS for each movie, and as such, be too slow as well as put unneeded pressure on the PMS

**Comment by ukdtom** [comment]
And Wiki page updated

**Comment by JPB46** [comment]
Well,  going full circle, I don't understand why Level 2 worked as it should 6 months ago, is broken now and can't be fixed.

**Comment by ukdtom** [comment]
Plex changed the way the WebAPI returns stuff
