### ISSUE TITLE
Add freebsd export path info to wiki

### ISSUE THREAD

**Issue by MingyaoLiu** [ukdtom/ExportTools.bundle#82]
Add this line to configuration for export path for freebsd users:

One Freebsd, the export path is something like this "/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.ExportTools/<'folder you created for exported files'>.

**Comment by MingyaoLiu** [comment]
to the wiki

**Comment by ukdtom** [comment]
That is a really bad path, that should never ever be used!

You should NEVER EVER put anything below  "Plug-in Support/Data", since that belongs to the plugins!

Also, if you remove a bundle, your exports will be gone as well!

**Comment by MingyaoLiu** [comment]
@ukdtom That's my bad, sorry about that.

However in the case of freebsd jail, the only place that is safe for the export would be the zfs directory mounted into the jail (usually where the plex library is), and I have tested it and not able to make it work. 

In my case my plex library is mounted to '/plex' to the plex jail, all the library works, however export path that contains '/plex/<export dir>' doesn't, and I'm not so sure why the mount point doesn't work.

If anyone can test this that would be great, you can close this thx.

**Comment by ukdtom** [comment]
Sadly not a freebsd dude, so clueless here, and already closed ;)

Maybe posting in the forum thread or the relevant server forum threads could make some freebsd dudes to help you out here?

**Comment by MingyaoLiu** [comment]
yah for sure.
