### ISSUE TITLE
Export path issue with Mac

### ISSUE THREAD

**Issue by tsmyles** [ukdtom/ExportTools.bundle#84]
I get “Select Preferences to set the export path”. Aaarrrgh!
I’ve cut and pasted a path using Terminal but the thing still gives me this message.
I’m on a Mac running 10.14.3
Here’s a screenshot.
![Screen Shot 2019-04-22 at 09 18 09](https://user-images.githubusercontent.com/49877733/56510741-9a41d100-64df-11e9-8ed1-7504f2a088e9.png)

**Comment by ukdtom** [comment]
What error msg?
Is your PMS running on this Mac?
Does the ExportTools Dir already exists?
Are you running PMS under your user account, if on this Mac?

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response
