### ISSUE TITLE
Movie export has no Location

### ISSUE THREAD

**Issue by WireCrazii** [ukdtom/ExportTools.bundle#96]
TV Show levels has `Location` in the `Show only 3` but Movie levels doesn't have that option in the list.
This option is really helpful if one of my disk fails I'll know what's missing.

**Comment by ukdtom** [comment]
Shows only shows the path to where the show is located.
If you export episodes, it more relevant to export for the individual file, which we do in `level 4` named `Part File Combined`
Same goes for movies, where you see the actual path and name of the file in `level 5` named `Part File Combined`

So unless you are asking for the complete file path to be added to `Special Level 3`for movies, this will not change

**Comment by ukdtom** [comment]
And forgot, if a disk fails, then this is much faster and better:
https://github.com/ukdtom/WebTools.bundle/wiki/FindMedia

**Comment by WireCrazii** [comment]
`Level 5` for movies is what I wanted. Tested and works like a charm. No disk failure.

Thanks a bunch.
